# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: (jw) joe whitsitt
email: contact@whitsitt.org
repository: joewhitsitt/joewhitsitt.github.io
description: >
  the personal website of joe whitsitt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joe.whitsitt.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joewhitsitt
github_username:  joewhitsitt

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:month/:day/:title
# Pagination.
paginate: 5
paginate_path: "/page:num"

disqus:
    shortname: joewhitsitt

google_analytics: UA-15494919-3

defaults:
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post
